// Code generated by bpf2go; DO NOT EDIT.
//go:build mips || mips64 || ppc64 || s390x

package collector

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"
	"structs"

	"github.com/cilium/ebpf"
)

type bpfEntryArgs struct {
	_         structs.HostLayout
	Args      [6]uint64
	Timestamp uint64
}

// loadBpf returns the embedded CollectionSpec for bpf.
func loadBpf() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_BpfBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load bpf: %w", err)
	}

	return spec, err
}

// loadBpfObjects loads bpf and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*bpfObjects
//	*bpfPrograms
//	*bpfMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func loadBpfObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := loadBpf()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// bpfSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type bpfSpecs struct {
	bpfProgramSpecs
	bpfMapSpecs
	bpfVariableSpecs
}

// bpfProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type bpfProgramSpecs struct {
	TraceAccept4Enter   *ebpf.ProgramSpec `ebpf:"trace_accept4_enter"`
	TraceAcceptEnter    *ebpf.ProgramSpec `ebpf:"trace_accept_enter"`
	TraceBindEnter      *ebpf.ProgramSpec `ebpf:"trace_bind_enter"`
	TraceCapsetEnter    *ebpf.ProgramSpec `ebpf:"trace_capset_enter"`
	TraceChmodEnter     *ebpf.ProgramSpec `ebpf:"trace_chmod_enter"`
	TraceChownEnter     *ebpf.ProgramSpec `ebpf:"trace_chown_enter"`
	TraceCloneEnter     *ebpf.ProgramSpec `ebpf:"trace_clone_enter"`
	TraceConnectEnter   *ebpf.ProgramSpec `ebpf:"trace_connect_enter"`
	TraceCreatEnter     *ebpf.ProgramSpec `ebpf:"trace_creat_enter"`
	TraceExecveEnter    *ebpf.ProgramSpec `ebpf:"trace_execve_enter"`
	TraceExecveExit     *ebpf.ProgramSpec `ebpf:"trace_execve_exit"`
	TraceExecveatEnter  *ebpf.ProgramSpec `ebpf:"trace_execveat_enter"`
	TraceFchmodEnter    *ebpf.ProgramSpec `ebpf:"trace_fchmod_enter"`
	TraceFchmodatEnter  *ebpf.ProgramSpec `ebpf:"trace_fchmodat_enter"`
	TraceFchownEnter    *ebpf.ProgramSpec `ebpf:"trace_fchown_enter"`
	TraceFchownatEnter  *ebpf.ProgramSpec `ebpf:"trace_fchownat_enter"`
	TraceForkEnter      *ebpf.ProgramSpec `ebpf:"trace_fork_enter"`
	TraceLchownEnter    *ebpf.ProgramSpec `ebpf:"trace_lchown_enter"`
	TraceListenEnter    *ebpf.ProgramSpec `ebpf:"trace_listen_enter"`
	TraceOpenEnter      *ebpf.ProgramSpec `ebpf:"trace_open_enter"`
	TraceOpenatEnter    *ebpf.ProgramSpec `ebpf:"trace_openat_enter"`
	TraceSetgidEnter    *ebpf.ProgramSpec `ebpf:"trace_setgid_enter"`
	TraceSetregidEnter  *ebpf.ProgramSpec `ebpf:"trace_setregid_enter"`
	TraceSetresgidEnter *ebpf.ProgramSpec `ebpf:"trace_setresgid_enter"`
	TraceSetresuidEnter *ebpf.ProgramSpec `ebpf:"trace_setresuid_enter"`
	TraceSetreuidEnter  *ebpf.ProgramSpec `ebpf:"trace_setreuid_enter"`
	TraceSetuidEnter    *ebpf.ProgramSpec `ebpf:"trace_setuid_enter"`
	TraceSocketEnter    *ebpf.ProgramSpec `ebpf:"trace_socket_enter"`
	TraceVforkEnter     *ebpf.ProgramSpec `ebpf:"trace_vfork_enter"`
	TraceWriteEnter     *ebpf.ProgramSpec `ebpf:"trace_write_enter"`
	TraceWritevEnter    *ebpf.ProgramSpec `ebpf:"trace_writev_enter"`
}

// bpfMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type bpfMapSpecs struct {
	ConfigMap      *ebpf.MapSpec `ebpf:"config_map"`
	EntryMap       *ebpf.MapSpec `ebpf:"entry_map"`
	Events         *ebpf.MapSpec `ebpf:"events"`
	SampleCounters *ebpf.MapSpec `ebpf:"sample_counters"`
}

// bpfVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type bpfVariableSpecs struct {
}

// bpfObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to loadBpfObjects or ebpf.CollectionSpec.LoadAndAssign.
type bpfObjects struct {
	bpfPrograms
	bpfMaps
	bpfVariables
}

func (o *bpfObjects) Close() error {
	return _BpfClose(
		&o.bpfPrograms,
		&o.bpfMaps,
	)
}

// bpfMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to loadBpfObjects or ebpf.CollectionSpec.LoadAndAssign.
type bpfMaps struct {
	ConfigMap      *ebpf.Map `ebpf:"config_map"`
	EntryMap       *ebpf.Map `ebpf:"entry_map"`
	Events         *ebpf.Map `ebpf:"events"`
	SampleCounters *ebpf.Map `ebpf:"sample_counters"`
}

func (m *bpfMaps) Close() error {
	return _BpfClose(
		m.ConfigMap,
		m.EntryMap,
		m.Events,
		m.SampleCounters,
	)
}

// bpfVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to loadBpfObjects or ebpf.CollectionSpec.LoadAndAssign.
type bpfVariables struct {
}

// bpfPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to loadBpfObjects or ebpf.CollectionSpec.LoadAndAssign.
type bpfPrograms struct {
	TraceAccept4Enter   *ebpf.Program `ebpf:"trace_accept4_enter"`
	TraceAcceptEnter    *ebpf.Program `ebpf:"trace_accept_enter"`
	TraceBindEnter      *ebpf.Program `ebpf:"trace_bind_enter"`
	TraceCapsetEnter    *ebpf.Program `ebpf:"trace_capset_enter"`
	TraceChmodEnter     *ebpf.Program `ebpf:"trace_chmod_enter"`
	TraceChownEnter     *ebpf.Program `ebpf:"trace_chown_enter"`
	TraceCloneEnter     *ebpf.Program `ebpf:"trace_clone_enter"`
	TraceConnectEnter   *ebpf.Program `ebpf:"trace_connect_enter"`
	TraceCreatEnter     *ebpf.Program `ebpf:"trace_creat_enter"`
	TraceExecveEnter    *ebpf.Program `ebpf:"trace_execve_enter"`
	TraceExecveExit     *ebpf.Program `ebpf:"trace_execve_exit"`
	TraceExecveatEnter  *ebpf.Program `ebpf:"trace_execveat_enter"`
	TraceFchmodEnter    *ebpf.Program `ebpf:"trace_fchmod_enter"`
	TraceFchmodatEnter  *ebpf.Program `ebpf:"trace_fchmodat_enter"`
	TraceFchownEnter    *ebpf.Program `ebpf:"trace_fchown_enter"`
	TraceFchownatEnter  *ebpf.Program `ebpf:"trace_fchownat_enter"`
	TraceForkEnter      *ebpf.Program `ebpf:"trace_fork_enter"`
	TraceLchownEnter    *ebpf.Program `ebpf:"trace_lchown_enter"`
	TraceListenEnter    *ebpf.Program `ebpf:"trace_listen_enter"`
	TraceOpenEnter      *ebpf.Program `ebpf:"trace_open_enter"`
	TraceOpenatEnter    *ebpf.Program `ebpf:"trace_openat_enter"`
	TraceSetgidEnter    *ebpf.Program `ebpf:"trace_setgid_enter"`
	TraceSetregidEnter  *ebpf.Program `ebpf:"trace_setregid_enter"`
	TraceSetresgidEnter *ebpf.Program `ebpf:"trace_setresgid_enter"`
	TraceSetresuidEnter *ebpf.Program `ebpf:"trace_setresuid_enter"`
	TraceSetreuidEnter  *ebpf.Program `ebpf:"trace_setreuid_enter"`
	TraceSetuidEnter    *ebpf.Program `ebpf:"trace_setuid_enter"`
	TraceSocketEnter    *ebpf.Program `ebpf:"trace_socket_enter"`
	TraceVforkEnter     *ebpf.Program `ebpf:"trace_vfork_enter"`
	TraceWriteEnter     *ebpf.Program `ebpf:"trace_write_enter"`
	TraceWritevEnter    *ebpf.Program `ebpf:"trace_writev_enter"`
}

func (p *bpfPrograms) Close() error {
	return _BpfClose(
		p.TraceAccept4Enter,
		p.TraceAcceptEnter,
		p.TraceBindEnter,
		p.TraceCapsetEnter,
		p.TraceChmodEnter,
		p.TraceChownEnter,
		p.TraceCloneEnter,
		p.TraceConnectEnter,
		p.TraceCreatEnter,
		p.TraceExecveEnter,
		p.TraceExecveExit,
		p.TraceExecveatEnter,
		p.TraceFchmodEnter,
		p.TraceFchmodatEnter,
		p.TraceFchownEnter,
		p.TraceFchownatEnter,
		p.TraceForkEnter,
		p.TraceLchownEnter,
		p.TraceListenEnter,
		p.TraceOpenEnter,
		p.TraceOpenatEnter,
		p.TraceSetgidEnter,
		p.TraceSetregidEnter,
		p.TraceSetresgidEnter,
		p.TraceSetresuidEnter,
		p.TraceSetreuidEnter,
		p.TraceSetuidEnter,
		p.TraceSocketEnter,
		p.TraceVforkEnter,
		p.TraceWriteEnter,
		p.TraceWritevEnter,
	)
}

func _BpfClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed bpf_bpfeb.o
var _BpfBytes []byte
